stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DOCKER_HUB_REPO: 'eugromanchenko/otus-gitlab'
  PATH_TO_DOCKERFILE: docker-monolith
  DOCKER_IMAGE_HUB: "${DOCKER_HUB_REPO}:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}"
  CERT_PATH: certs

build_job:
  image: docker:latest
  service:
    - docker:dind
  stage: build
  script:
    - cd ${PATH_TO_DOCKERFILE}
    - docker build -t ${DOCKER_IMAGE_HUB} .
    - docker login -u ${DOCKER_HUB_LOGIN} -p ${DOCKER_HUB_PASS}
    - docker push ${DOCKER_IMAGE_HUB}

test_unit_job:
  stage: test
  image: ruby:2.4.2
  services:
    - mongo:latest
  before_script:
    - cd reddit
    - bundle install
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo $GOOGLE_SA_JSON >> /tmp/google_sa.json
    - export GOOGLE_APPLICATION_CREDENTIALS=/tmp/google_sa.json
    - apk update && apk add ca-certificates curl jq
    - base=https://github.com/docker/machine/releases/download/v0.14.0 && curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine && install /tmp/docker-machine /usr/local/bin/docker-machine
    - docker-machine -s ${CERT_PATH} create --driver google --google-project docker-201811 --google-machine-image https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts --google-machine-type n1-standard-1 --google-zone europe-west1-b ${INSTANCE_NAME}
    - eval $(docker-machine -s ${CERT_PATH} env --shell sh ${INSTANCE_NAME})
    - docker pull ${DOCKER_IMAGE_HUB}
    - docker run -d -p 9292:9292 ${DOCKER_IMAGE_HUB}
  environment:
    name: branch/$CI_COMMIT_REF_NAME
  only:
    - branches
  except:
    - master

kill branch review:
  stage: review
  image: docker:latest
  services:
    - docker:dind
  when: manual
  script:
    - echo $GOOGLE_SA_JSON >> /tmp/google_sa.json
    - export GOOGLE_APPLICATION_CREDENTIALS=/tmp/google_sa.json
    - apk update && apk add ca-certificates curl jq
    - base=https://github.com/docker/machine/releases/download/v0.14.0 && curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine && install /tmp/docker-machine /usr/local/bin/docker-machine
    - docker-machine -s ${CERT_PATH} rm -y ${INSTANCE_NAME}

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
