dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: jsIuWy9asjiaudFOgLcfgbUq+o7QHhu5zPufYlTkntJ5Nmmrn1giLOPN3Y5JVMPU/QJt63SWk8l8MvBfNbLk2/NevlC65t4q9bpeWlvpX/IH2bsxlxy1tr79cQe/Hy5dw2Ng3wUTovxNBj7PQx3CeEjpdedKGazkeK1CiW5vlhiYa2krq6A7gDXL041g/0Vktj/fnZ0/bjulootxkgupRIbXSwoG3UmUabzgNWuzRM6bNUeLOs7jt4TIJVybrkX5KA4/jnBCqPvl1xsugzPw5oMUypWGHWGTDhROZ3LFlKXj2tCRGgYV1f+pK4qbFIGTiviOOxECadagecDU9hLUR7BmbmzkJR2TBCqvkOvE3Csa8zT3YQuYaC/2UwfdfGhBTw6NlE6YrVM0Eo1wzlF4vEntQzfjblJrSs4cJhNrrWRFMM/E+i2mfY81h5l6LIUVHALqUxnk/RB5Ug82ZonvXwmBMZL81IUUs47YkPZzrAidWvBtkRYKOjPCo30vR4dgY3me0i/gYAX11nYuFH2t8bHGMDvObUZlezZWHkDLnSkcq+7W5f6fojnMe9Y92xdXyKv6qJvpNqaMTnczVDTd12gotjt2Zy5LC3Y+AQg7eu0Ugk/j57Diw142wi65YWjOyzm9+G9cZM6hVT39pTws2gBwpvts25V//e+RsePVFjg=
