comment:
  image:
    repository: eugromanchenko/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: eugromanchenko/post
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: eugromanchenko/ui
    tag: latest
    service:
      externalPort: 9292
