apiVersion: 1

deleteDatasources:
  - name: Prometheus Server
    orgId: 1

datasources:
  - name: Prometheus Server
    type: prometheus
    access: proxy
    editable: true
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1 
