global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#eugeny_romanchenko'
