---
- name: Install Docker package
  hosts: all 
  become: true

  tasks:
    - name: Install supported package
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present 
        update_cache: yes

    - name: Download Docker repo key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg

    - name: Add Docker repo key
      apt_key:
        file: /tmp/docker.gpg
        state: present


    - name: Add Docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes
